language: go

go:
- '1.11'

env:
- GO111MODULE=on

before_install:
  - sudo apt-get install -y upx-ucl

git:
  depth: 1

notifications:
  email: false

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "build/gudgeon"
  skip_cleanup: true
  on:
    tags: true