language: go

go:
- '1.11'

env:
- GO111MODULE=on

before_install:
  - export VERSION=${TRAVIS_TAG:$(git rev-parse --abbrev-ref HEAD)}
  - export NUMBER=${VERSION:1}

git:
  depth: 1

notifications:
  email: false

script:
  - make test

before_deploy:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -y upx-ucl ruby ruby-dev build-essential rpm libsqlite3-dev gcc-multilib and g++-multilib libc6-dev-i386 libsqlite3-dev:i386
  - gem install --no-ri --no-rdoc fpm
  - make prepare  
  - make download
  - make build
  - OS_BIN_ARCH=amd64 OS_ARCH=x86_64 make rpm
  - OS_BIN_ARCH=386 OS_ARCH=i686 make rpm
  - OS_BIN_ARCH=arm OS_ARCH=arm make rpm
  - OS_BIN_ARCH=amd64 OS_ARCH=x86_64 make deb
  - OS_BIN_ARCH=386 OS_ARCH=i386 make deb
  - OS_BIN_ARCH=arm OS_ARCH=armhf make deb

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: build/gudgeon*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true