language: go

# enable docker for xgo
services:
- docker

# go version to use
go:
- '1.11'

# explicit import path
go_import_path: github.com/chrisruffalo/gudgeon

# establish that go modules are in use
env:
- GO111MODULE=on

# export versions into a format compatible with make file
before_install:
  - export VERSION=${TRAVIS_TAG:$(git rev-parse --abbrev-ref HEAD)}
  - export NUMBER=${VERSION:1}
  - if [[ ""=="$NUMBER" ]]; then export NUMBER=$(git tag | sort -V | tail -n 1 | cut --complement -b 1); fi

# only need the current depth
git:
  depth: 1

# no email notifications
notifications:
  email: false

# make full use of cache.
before_script:
  # install dependencies
  - sudo apt-get update
  - sudo apt-get install -y upx-ucl ruby ruby-dev build-essential rpm libsqlite3-dev gcc-multilib and g++-multilib
  - gem install --no-ri --no-rdoc fpm
  # pull xgo container
  - docker pull karalabe/xgo-latest
  # prepare build environment
  - make prepare  

# to "succeed" the script only needs to build and test
script:
  - make test

# after success do all of the build stuff (within scope of the cache, hopefully)
after_success:
  - make download
  # build binaries
  - make GOOS_LIST="linux" GOARCH_LIST="386 amd64" build
  - make buildxgo
  # compress binaries
  - make compress
  # package targets
  - OS_BIN_ARCH=amd64 OS_ARCH=x86_64 make rpm
  - OS_BIN_ARCH=386 OS_ARCH=i686 make rpm
  - OS_BIN_ARCH=amd64 OS_ARCH=x86_64 make deb
  - OS_BIN_ARCH=386 OS_ARCH=i386 make deb
  - BIN_TARGET=gudgeon-linux-arm-5 OS_ARCH=arm5 make rpm
  - BIN_TARGET=gudgeon-linux-arm-5 OS_ARCH=arm5 make deb
  - BIN_TARGET=gudgeon-linux-arm-6 OS_ARCH=arm6 make rpm
  - BIN_TARGET=gudgeon-linux-arm-6 OS_ARCH=arm6 make deb

before_deploy:
  # make docker build(s)
  - BIN_TARGET=gudgeon-linux-amd64 make docker
  # push build(s) to docker cloud
  - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME"
  - make dockerpush
  - DOCKER_TAG=latest make dockerpush

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: build/gudgeon*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true